Reorganize the QS back into a subfolder structure.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,97 +2,133 @@ version: 2.1
 
 commands:
   prepare:
-    steps:
+    setup:
+      - run:
+          name: Configure environment
+          command: |
+            apk update
+
       - checkout
+
       - run:
           name: Perform composer self-update
           command: sudo composer self-update
-      - restore_cache:
-          keys:
-            - composer-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}
-            - composer-v1-{{ .Environment.CIRCLE_JOB }}
+
       - run:
-          name: Enable code coverage
+          name: Install dependencies
           command: |
-            sudo pecl install pcov
-            sudo docker-php-ext-enable pcov
-            sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
-            sudo docker-php-ext-install posix
-            sudo docker-php-ext-install pcntl
+            EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
+            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+            ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+            if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
+                >&2 echo 'ERROR: Invalid installer checksum'
+                rm composer-setup.php
+                exit 1
+            fi
+
+            php composer-setup.php --quiet
+            RESULT=$?
+            rm composer-setup.php
+
+            php composer.phar install --no-interaction --prefer-dist
+
+  setup-pcov:
+    steps:
       - run:
-          name: Install composer dependencies
-          command: composer install -n --prefer-dist
-      - run:
-          name: Update composer dependencies
-          command: composer update --prefer-dist --no-interaction
-      - persist_to_workspace:
-          root: .
-          paths:
-            - composer.*
-            - .snyk
-      - save_cache:
-          key: composer-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}
-          paths:
-            - vendor
+          name: Setup code coverage (PCOV)
+          command: |
+            apk add autoconf gcc make musl-dev
+            pecl install pcov
+            docker-php-ext-enable pcov
 
   run-phpinsights:
     steps:
       - run:
-          name: Run PHP Insights code quality analysis
-          command: php ./vendor/bin/phpinsights -v --no-interaction
+          name: Run code quality analysis (PHP Insights)
+          command: php -d memory-limit=-1 ./vendor/bin/phpinsights -v --no-interaction --min-quality=100 --min-complexity=50 --min-architecture=100 --min-style=100
 
   run-phpstan:
     steps:
       - run:
-          name: Run PHPStan static code analysis
-          command: php ./vendor/bin/phpstan analyse --ansi --memory-limit 512M
+          name: Run static code analysis (PHPStan)
+          command: php -d memory_limit=-1 ./vendor/bin/phpstan analyse --ansi
 
   run-psalm:
     steps:
       - run:
-          name: Run Psalm static code analysis
-          command: php ./vendor/bin/psalm --no-cache
+          name: Run static code analysis (Psalm)
+          command: php -d memory_limit=-1 ./vendor/bin/psalm
+
+  run-snyk:
+    steps:
+      - run:
+          name: Run vulnerabilities tests (Snyk)
+          command: |
+            apk add npm
+            npm install -g snyk
+            snyk test --dev --org=auth0-sdks --project-name=auth0-PHP
 
 jobs:
-  php_7_4:
+  phpinsights:
+    parameters:
+      php:
+        type: string
     docker:
-      - image: circleci/php:7.4
+      - image: php:<< parameters.php >>-cli-alpine
     steps:
-      - prepare
+      - setup
       - run-phpinsights
-      - run-phpstan
-      - run-psalm
-  php_8_0:
+  phpstan:
+    parameters:
+      php:
+        type: string
     docker:
-      - image: circleci/php:8.0
+      - image: php:<< parameters.php >>-cli-alpine
     steps:
-      - prepare
-      - run-phpinsights
+      - setup
       - run-phpstan
+  psalm:
+    parameters:
+      php:
+        type: string
+    docker:
+      - image: php:<< parameters.php >>-cli-alpine
+    steps:
+      - setup
       - run-psalm
   snyk:
+    parameters:
+      php:
+        type: string
     docker:
-      - image: snyk/snyk-cli:composer
+      - image: php:<< parameters.php >>-cli-alpine
     steps:
-      - attach_workspace:
-          at: .
-      - run: snyk test
+      - setup
+      - run-snyk
 
 workflows:
-  test-php-versions:
+  test:
     jobs:
-      - php_7_4
-      - php_8_0
-
-  vulnerability-check:
-    jobs:
-      - php_7_4
-      - php_8_0
+      - phpinsights:
+          matrix:
+            parameters:
+              php: ["7.4", "8.0"]
+      - phpstan:
+          matrix:
+            parameters:
+              php: ["7.4", "8.0"]
+      - psalm:
+          matrix:
+            parameters:
+              php: ["7.4", "8.0"]
+      - hold:
+          type: approval
       - snyk:
-          filters:
-            branches:
-              only:
-                - master
-          context: snyk-env
+          matrix:
+            parameters:
+              php: ["7.4", "8.0"]
+          context:
+            - snyk-env
           requires:
-            - php_8_0
+            - hold
